const express = require('express');
const cors = require('cors');
const multer = require('multer');
const path = require('path');
const { parseAPICode } = require('./parser');
const { generateDocumentation } = require('./ai-generator');
const { analyzeQuality } = require('./quality-checker');

// Load env
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3001;
const upload = multer({ storage: multer.memoryStorage() });

app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true }));

// Serve frontend static files
app.use(express.static(path.join(__dirname, '..', 'frontend')));

// Health check
app.get('/api/health', (req, res) => {
  res.json({
    status: 'ok',
    engine: 'DocForge AI',
    llm: process.env.GEMINI_API_KEY ? 'Google Gemini 2.0 Flash' : 'Gemini Fallback Intelligence Engine',
    timestamp: new Date().toISOString()
  });
});

// Main endpoint: Generate documentation from code
app.post('/api/generate', async (req, res) => {
  try {
    const { code, language } = req.body;

    if (!code || code.trim().length === 0) {
      return res.status(400).json({ error: 'No code provided' });
    }

    console.log(`\n📄 Received code (${code.length} chars), language: ${language || 'auto-detect'}`);

    const parsedEndpoints = parseAPICode(code, language);
    console.log(`🔍 Parsed ${parsedEndpoints.length} endpoints`);

    const documentation = await generateDocumentation(code, parsedEndpoints, language);
    console.log(`✨ Generated documentation with Security Audit & SDK Snippets`);

    const quality = analyzeQuality(documentation);
    console.log(`📊 Quality score: ${quality.score}% (${quality.grade})`);

    res.json({
      success: true,
      parsedEndpoints,
      documentation,
      quality,
      metadata: {
        language: language || 'auto-detected',
        endpointCount: parsedEndpoints.length,
        llmUsed: process.env.GEMINI_API_KEY ? 'Google Gemini 2.0 Flash' : 'Gemini Heuristic Engine',
        generatedAt: new Date().toISOString()
      }
    });
  } catch (error) {
    console.error('❌ Generation error:', error);
    res.status(500).json({
      error: 'Failed to generate documentation',
      message: error.message
    });
  }
});

// File upload endpoint
app.post('/api/upload', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file uploaded' });
    }

    const code = req.file.buffer.toString('utf-8');
    const filename = req.file.originalname;
    const ext = path.extname(filename).toLowerCase();

    const langMap = {
      '.py': 'python',
      '.js': 'javascript',
      '.ts': 'typescript',
      '.java': 'java',
      '.go': 'go',
      '.json': 'json',
      '.yaml': 'yaml',
      '.yml': 'yaml'
    };
    const language = langMap[ext] || 'auto';

    console.log(`\n📁 File uploaded: ${filename} (${code.length} chars)`);

    const parsedEndpoints = parseAPICode(code, language);
    const documentation = await generateDocumentation(code, parsedEndpoints, language);
    const quality = analyzeQuality(documentation);

    res.json({
      success: true,
      parsedEndpoints,
      documentation,
      quality,
      metadata: {
        filename,
        language,
        endpointCount: parsedEndpoints.length,
        llmUsed: process.env.GEMINI_API_KEY ? 'Google Gemini 2.0 Flash' : 'Gemini Heuristic Engine',
        generatedAt: new Date().toISOString()
      }
    });
  } catch (error) {
    console.error('❌ Upload error:', error);
    res.status(500).json({
      error: 'Failed to process uploaded file',
      message: error.message
    });
  }
});

// Interactive AI Mock Server Runner
app.all('/api/mock-execute', (req, res) => {
  const { targetMethod, targetPath, payload } = req.body || req.query;
  
  res.json({
    status: 200,
    statusText: 'OK (AI Mock Server)',
    executedAt: new Date().toISOString(),
    request: {
      method: targetMethod || req.method,
      path: targetPath || '/api/resource',
      headers: {
        'content-type': 'application/json',
        'authorization': 'Bearer mock_jwt_token_sample'
      },
      payload: payload || null
    },
    response: {
      message: 'Simulated API execution response generated by DocForge AI Live Sandbox',
      result: payload ? { id: Math.floor(Math.random() * 9000) + 1000, ...payload } : { id: 101, status: 'active' }
    }
  });
});

// Export to OpenAPI 3.0 JSON
app.post('/api/export/openapi', (req, res) => {
  const { documentation } = req.body;
  if (!documentation || !Array.isArray(documentation)) {
    return res.status(400).json({ error: 'Documentation data required' });
  }

  const openapiSpec = {
    openapi: "3.0.0",
    info: {
      title: "DocForge AI Generated OpenAPI Spec",
      version: "1.0.0",
      description: "Auto-generated API documentation by DocForge AI Generator"
    },
    paths: {}
  };

  documentation.forEach(doc => {
    if (!openapiSpec.paths[doc.path]) {
      openapiSpec.paths[doc.path] = {};
    }
    const methodLower = doc.method.toLowerCase();
    openapiSpec.paths[doc.path][methodLower] = {
      summary: doc.summary,
      description: doc.description,
      tags: doc.tags || ['default'],
      parameters: (doc.parameters || []).map(p => ({
        name: p.name,
        in: p.in || 'query',
        required: p.required || false,
        schema: { type: p.type || 'string' },
        description: p.description
      })),
      responses: {
        "200": {
          description: "Success",
          content: {
            "application/json": {
              example: doc.responses?.[0]?.example || {}
            }
          }
        }
      }
    };
  });

  res.json(openapiSpec);
});

// Catch-all: serve frontend
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, '..', 'frontend', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`\n🚀 DocForge AI running at http://localhost:${PORT}`);
  console.log(`⚡ Engine: ${process.env.GEMINI_API_KEY ? 'Google Gemini 2.0 Flash' : 'Gemini Fallback Intelligence Engine'}`);
});
